---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: nginx-web
spec:
  selector:
    app: mynginx
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePorrt: 30002
